---
title: "Mapa de áreas silvestres protegidas (ASP) en la Gran Área Metropolitana"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leafem)
library(esri2sf)
library(raster)

#--------------- URL de geoservicios --------------

url_agfs_limite_gam <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_gam/FeatureServer/0"

url_asp_gam <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-biodiversidad/main/gam/asp_corredores_gam.geojson"

url_raster_uso_tierra <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-uso-tierra/master/gam/USO_COBERTURA_GAM_WEB.tif"

#--------------- Objetos sf y raster ---------------

# Límite de la GAM
sf_limite_gam <-
  esri2sf(url_agfs_limite_gam)

# Límite de la GAM (reproyectado a Web Mercator)
sf_limite_gam_web <- 
  sf_limite_gam %>%
  st_transform(3857)

# ASP
sf_asp_gam <- 
  st_read(url_asp_gam)

# Capa raster de uso de la tierra (en Web Mercator)
raster_uso_tierra <-
  raster(url_raster_uso_tierra) %>%
  crop(sf_limite_gam_web) %>%
  mask(sf_limite_gam_web)

#---------------- Paletas de colores ---------------

colores_uso_tierra <- 
  c(rgb(236,243,228,maxColorValue=255), rgb(178,209,225,maxColorValue=255), 
    rgb(52,130,100, maxColorValue=255), rgb(43,99,89,   maxColorValue=255),
    rgb(122,173,111,maxColorValue=255), rgb(169,183,107,maxColorValue=255),
    rgb(49,129,117, maxColorValue=255), rgb(69,155,122, maxColorValue=255)
  )

etiquetas_uso_tierra <- 
  c("Zonas urbanas continuas y discontinuas", "Aguas continentales", 
    "Bosque secundario temprano", "Bosque secundario medio y tardío",
    "Café", "Fresas, flores y ornamentales", 
    "Hortalizas, raíces y tubérculos", "Pastos con árboles y limpios"
  )

values_uso_tierra <- c(1, 2, 3, 4, 5, 6, 7, 8)

pal <- colorFactor(
  palette = colores_uso_tierra, 
  domain = values_uso_tierra,
  na.color = "transparent"
)

```

Column {data-width=800}
-----------------------------------------------------------------------

### {data-height=20}
**Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies).**

### 

```{r}

leaflet() %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_gam,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite de la GAM"
  ) %>%
  addPolygons(
    data = sf_asp_gam,
    color = "Yellow",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 4.0,
    popup = paste(sf_asp_gam$siglas_cat, sf_asp_gam$nombre_asp),
    label = ~sf_asp_gam$codigo,
    labelOptions = labelOptions(noHide = T, direction = "bottom"),
    group = "ASP"
  ) %>%  
  addRasterImage(
    raster_uso_tierra, 
    colors = pal, 
    opacity = 1,
    group = "Uso de la tierra"
  ) %>%
  addLegend(
    title = "Uso de la tierra", 
    position = "bottomright",
    colors = colores_uso_tierra, 
    labels = etiquetas_uso_tierra,
    group = "Uso de la tierra"
  ) %>%  
  addLayersControl(
    baseGroups = c("CartoDB Dark Matter", "OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Límite de la GAM", "ASP", "Uso de la tierra"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$CartoDB.DarkMatter
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates()

```

Column {data-width=200}
-----------------------------------------------------------------------

### {data-height=50}
* 13.8 % GAM  
* 24.468 ha en ASP

###
**Áreas sivestres protegidas**  

* C01 - CBI Río María Aguilar  
* C02 - CBI Río Torres Reserva de la Biosfera  
* P02 - Braulio Carrillo  
* P23 - Volcan Irazú  
* P24 - Tapantí-Macizo de la Muerte  
* R02 - Cordillera Volcanica Central  
* R06 - Grecia  
* Z01 - Cerro de Escazú  
* Z04 - Cerros de La Carpintera  
* Z05 - El Rodeo  
* Z06 - Cerro Atenas  
* Z08 - Río Tiribí  
* Z10 - Río Navarro-Río Sombrero